version: 2.0

workspace: &workspace
  ~/android-simple-boilerplate

config_android: &config_android
  docker:
    - image: circleci/android:api-29
  working_directory: *workspace
  environment:
    JAVA_TOOL_OPTIONS: "-Xmx1024m"
    GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Dkotlin.incremental=false -Dkotlin.compiler.execution.strategy=in-process"
    TERM: dumb

update_sdk: &update_sdk
  run:
    name: Update SDK
    command: |
      yes | sdkmanager --licenses || true
      sdkmanager "platform-tools" "platforms;android-29"

attach_workspace: &attach_workspace
  attach_workspace:
    at: *workspace

persist_workspace: &persist_workspace
  persist_to_workspace:
    root: *workspace
    paths:
      - ./*/build

restore_cache: &restore_cache
  restore_cache:
    key: gradle-{{ checksum "build.gradle" }}-{{ checksum "buildSrc/src/main/java/buildsrc/Dependencies.kt" }}

save_cache: &save_cache
  save_cache:
    key: gradle-{{ checksum "build.gradle" }}-{{ checksum "buildSrc/src/main/java/buildsrc/Dependencies.kt" }}
    paths:
      - ~/.gradle/caches
      - ~/.gradle/wrapper

jobs:
  build_debug:
    <<: *config_android
    steps:
      - <<: *update_sdk
      - checkout
      - <<: *restore_cache
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies
      - run:
          name: Assemble debug APKs
          command: ./gradlew assembleDebug
      - <<: *save_cache
      - store_artifacts:
          path: app/build/outputs
          destination: outputs
      - <<: *persist_workspace

  run_tests:
    <<: *config_android
    steps:
      - checkout
      - <<: *attach_workspace
      - <<: *restore_cache
      - run:
          name: Check app and dependencies
          command: ./gradlew testDebugUnitTest
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit

workflows:
  version: 2
  build_test:
    jobs:
      - build_debug
      - run_tests:
          requires:
            - build_debug
